# Generated by Django 5.0 on 2025-04-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursales",
            name="destinatarios_email",
            field=models.TextField(
                blank=True,
                help_text="Lista de correos electrónicos separados por coma, por ejemplo: correo1@dominio.com, correo2@dominio.com",
            ),
        ),
    ]
