# Generated by Django 5.0.14 on 2025-08-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_protect_sucursal_cascade"),
        ("sucursales", "0002_sucursales_destinatarios_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sucursales.sucursales"
            ),
        ),
    ]
