# Generated by Django 5.0.14 on 2025-04-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="informe_sit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idPerInforme", models.IntegerField()),
                ("numeroinforme", models.IntegerField()),
                ("lugarcontrol", models.CharField(max_length=150)),
                ("legajo", models.IntegerField()),
                ("apellido", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("empresa", models.CharField(max_length=100)),
                ("cuit", models.CharField(max_length=13)),
                ("domicilio", models.CharField(max_length=100)),
                ("linea", models.CharField(max_length=10)),
                ("ficha", models.CharField(max_length=20)),
                ("mediocomunicacion", models.CharField(max_length=100)),
                ("fechahoracontrol", models.DateTimeField()),
                ("fechacomunicacion", models.DateTimeField()),
                ("turnoafectado", models.DateTimeField()),
                ("descripcion", models.CharField(max_length=400)),
                ("emisor", models.CharField(max_length=100)),
                ("descargo", models.CharField(max_length=400)),
            ],
            options={
                "db_table": "perinformepersonal",
                "managed": False,
            },
        ),
    ]
