# Generated by Django 5.0.9 on 2025-04-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0001_initial"),
        ("informes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informe",
            name="empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="empleados.empleado",
            ),
        ),
    ]
