# Generated by Django 5.0.9 on 2025-04-17 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0002_alter_informe_empleado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informe",
            name="fecha_hora",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
