# Generated by Django 5.0 on 2025-04-18 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0003_alter_informe_fecha_hora"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoinforme",
            name="fecha_subida",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="videoinforme",
            name="video",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
