# Generated by Django 5.0 on 2025-04-18 13:36

import informes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0004_videoinforme_fecha_subida_alter_videoinforme_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoinforme",
            name="video",
            field=models.FileField(upload_to=informes.models.ruta_archivo),
        ),
    ]
