# Generated by Django 5.0 on 2025-04-18 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0005_alter_videoinforme_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialEnvioInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "destinatarios",
                    models.TextField(help_text="Lista de correos separados por coma"),
                ),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_envios",
                        to="informes.informe",
                    ),
                ),
            ],
        ),
    ]
