# Generated by Django 5.0.9 on 2025-04-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0006_historialenvioinforme"),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="origen",
            field=models.CharField(
                choices=[
                    ("Sistemas", "Sistemas"),
                    ("Guardia", "Guardia"),
                    ("RRHH", "RRHH"),
                    ("Siniestros", "Siniestros"),
                ],
                default="Sistemas",
                max_length=20,
            ),
        ),
    ]
