# Generated by Django 5.0.14 on 2025-05-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0007_informe_origen"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpedienteInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_expediente", models.IntegerField()),
                (
                    "informe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expediente",
                        to="informes.informe",
                    ),
                ),
            ],
        ),
    ]
