# Generated by Django 5.0.14 on 2025-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0008_expedienteinforme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informe",
            name="origen",
            field=models.CharField(
                choices=[
                    ("Sistemas", "Sistemas"),
                    ("Guardia", "Guardia"),
                    ("RRHH", "RRHH"),
                    ("Taller", "Taller"),
                    ("Siniestros", "Siniestros"),
                ],
                default="Sistemas",
                max_length=20,
            ),
        ),
    ]
