# Generated by Django 5.0.14 on 2025-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0009_alter_informe_origen"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedienteinforme",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[("I", "Informe"), ("S", "Siniestro"), ("D", "Desestimar")],
                max_length=1,
                null=True,
            ),
        ),
    ]
