# Generated by Django 5.0.14 on 2025-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0010_expedienteinforme_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedienteinforme",
            name="comentario",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
