# Generated by Django 5.0.14 on 2025-05-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0011_expedienteinforme_comentario"),
        ("sucursales", "0001_initial"),  # Agregar dependencia de sucursales
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='sucursal',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,  # CAMBIO CRÍTICO: CASCADE → PROTECT
                to='sucursales.sucursales',
                help_text="Protegido: No se puede eliminar sucursal si tiene informes"
            ),
        ),
    ]