# Generated by Django 5.0.14 on 2025-08-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0012_protect_sucursal_cascade"),
        ("sucursales", "0002_sucursales_destinatarios_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informe",
            name="origen",
            field=models.CharField(
                choices=[
                    ("Sistemas", "Sistemas"),
                    ("Guardia", "Guardia"),
                    ("RRHH", "RRHH"),
                    ("Taller", "Taller"),
                    ("Siniestros", "Siniestros"),
                    ("Inspectores", "Inspectores"),
                ],
                default="Sistemas",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="informe",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sucursales.sucursales"
            ),
        ),
    ]
