# Generated by Django 5.0.9 on 2025-11-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0013_alter_informe_origen_alter_informe_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Origen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no aparecerá en los formularios', verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Origen',
                'verbose_name_plural': 'Orígenes',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
