# Generated by Django 5.0.9 on 2025-11-20

from django.db import migrations


def crear_origenes(apps, schema_editor):
    """
    Crea los registros de origen basados en los valores hardcodeados anteriores
    """
    Origen = apps.get_model('informes', 'Origen')

    origenes_datos = [
        {'nombre': 'Sistemas', 'orden': 1, 'activo': True, 'descripcion': 'Informes generados por el área de Sistemas'},
        {'nombre': 'Guardia', 'orden': 2, 'activo': True, 'descripcion': 'Informes generados por Guardia'},
        {'nombre': 'RRHH', 'orden': 3, 'activo': True, 'descripcion': 'Informes generados por Recursos Humanos'},
        {'nombre': 'Taller', 'orden': 4, 'activo': True, 'descripcion': 'Informes generados por Taller'},
        {'nombre': 'Siniestros', 'orden': 5, 'activo': True, 'descripcion': 'Informes generados por área de Siniestros'},
        {'nombre': 'Inspectores', 'orden': 6, 'activo': True, 'descripcion': 'Informes generados por Inspectores'},
    ]

    for datos in origenes_datos:
        Origen.objects.get_or_create(
            nombre=datos['nombre'],
            defaults={
                'orden': datos['orden'],
                'activo': datos['activo'],
                'descripcion': datos['descripcion']
            }
        )


def eliminar_origenes(apps, schema_editor):
    """
    Función de reversión: elimina todos los orígenes creados
    """
    Origen = apps.get_model('informes', 'Origen')
    Origen.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0014_crear_modelo_origen'),
    ]

    operations = [
        migrations.RunPython(crear_origenes, eliminar_origenes),
    ]
