# Generated by Django 5.0.9 on 2025-11-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0015_poblar_origenes'),
    ]

    operations = [
        # Renombrar el campo antiguo origen a origen_old
        migrations.RenameField(
            model_name='informe',
            old_name='origen',
            new_name='origen_old',
        ),
        # Agregar nuevo campo origen_new como ForeignKey nullable
        migrations.AddField(
            model_name='informe',
            name='origen_new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='informes.origen',
                verbose_name='Origen',
                help_text='Origen del informe'
            ),
        ),
    ]
