# Generated by Django 5.0.9 on 2025-11-20

from django.db import migrations


def migrar_datos_origen(apps, schema_editor):
    """
    Migra los datos del campo origen_old (CharField) al campo origen_new (ForeignKey)
    """
    Informe = apps.get_model('informes', 'Informe')
    Origen = apps.get_model('informes', 'Origen')

    # Obtener todos los informes
    informes = Informe.objects.all()

    # Mapeo de valores antiguos a los nuevos registros de Origen
    for informe in informes:
        if informe.origen_old:
            try:
                # Buscar el origen correspondiente por nombre
                origen_obj = Origen.objects.get(nombre=informe.origen_old)
                informe.origen_new = origen_obj
                informe.save(update_fields=['origen_new'])
            except Origen.DoesNotExist:
                # Si el origen no existe, intentar con 'Sistemas' como fallback
                try:
                    origen_obj = Origen.objects.get(nombre='Sistemas')
                    informe.origen_new = origen_obj
                    informe.save(update_fields=['origen_new'])
                    print(f"⚠️  Informe {informe.id}: origen '{informe.origen_old}' no encontrado, usando 'Sistemas'")
                except Origen.DoesNotExist:
                    print(f"❌ Error: No se pudo migrar el informe {informe.id}")


def revertir_migracion(apps, schema_editor):
    """
    Función de reversión: copia los datos de vuelta
    """
    Informe = apps.get_model('informes', 'Informe')

    for informe in Informe.objects.all():
        if informe.origen_new:
            informe.origen_old = informe.origen_new.nombre
            informe.save(update_fields=['origen_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0016_agregar_campo_origen_nuevo'),
    ]

    operations = [
        migrations.RunPython(migrar_datos_origen, revertir_migracion),
    ]
