# Generated by Django 5.0.9 on 2025-11-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0017_migrar_datos_origen'),
    ]

    operations = [
        # Eliminar el campo antiguo origen_old
        migrations.RemoveField(
            model_name='informe',
            name='origen_old',
        ),
        # Renombrar origen_new a origen
        migrations.RenameField(
            model_name='informe',
            old_name='origen_new',
            new_name='origen',
        ),
        # Hacer el campo no nullable (ahora que todos los datos están migrados)
        migrations.AlterField(
            model_name='informe',
            name='origen',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='informes.origen',
                verbose_name='Origen',
                help_text='Origen del informe'
            ),
        ),
    ]
