# Generated by Django 5.0.9 on 2025-11-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0018_finalizar_migracion_origen'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='origenes',
            field=models.ManyToManyField(
                blank=True,
                help_text='Orígenes que el usuario puede usar al crear/editar informes',
                related_name='usuarios',
                to='informes.origen',
                verbose_name='Orígenes permitidos'
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='puede_usar_todos_origenes',
            field=models.BooleanField(
                default=False,
                help_text='Si está marcado, el usuario podrá usar todos los orígenes sin restricciones',
                verbose_name='¿Puede usar todos los orígenes?'
            ),
        ),
    ]
