# Generated by Django 5.0.9 on 2025-04-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='Buses',
        ),
    ]
