# Generated by Django 5.0.9 on 2025-04-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_rename_bus_buses'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='ficha',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
