# Generated by Django 5.0.14 on 2025-04-23 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0004_marca_remove_buses_marca_alter_buses_id_modelo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buses",
            options={"verbose_name": "Bus", "verbose_name_plural": "Buses"},
        ),
        migrations.AddField(
            model_name="buses",
            name="actualizado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="buses",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="buses",
            name="ficha",
            field=models.IntegerField(unique=True),
        ),
    ]
