# Generated by Django 5.0.14 on 2025-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0005_alter_buses_options_buses_actualizado_buses_creado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buses",
            name="estado",
            field=models.BooleanField(default=True),
        ),
    ]
